Catch key error for background colour
maxammann/trello-to-deck pull request #15
Opened 2020-11-11 23:01 UTC by connorjward

I was getting a `KeyError` when setting the background colour (which in my case was `"grey"`). This is now checked for and falls back to the default value of `"green"`. The `color_map` variable could definitely be extended to include `"grey"` but I think that this is more robust.

2020-11-13 18:22 UTC, maxammann requested changes

2020-11-13 18:22 UTC, maxammann commented on trello_to_deck/trello.py
> +            background_color = color_map[trello_json.prefs.background]
the try-catch should only enclose the array access:
```suggestion
            try:
                background_color = color_map[trello_json.prefs.background] 
            except KeyError:
....
```

2020-11-13 18:22 UTC, maxammann commented on trello_to_deck/trello.py
> +            background_color = "green"
Shouldn't background_color already be a hex value? You can access color_map[None] here I think. 
```suggestion
            background_color = color_map[None] 
```

2020-11-13 18:22 UTC, maxammann commented on trello_to_deck/trello.py
> +        background_color = "green"
```suggestion
        background_color = color_map[None]
```

2020-11-15 20:17 UTC, connorjward commented
I got a little bit confused by all your suggestions but I think I've made it do what you want. Definitely squash merge this because the history is now quite messy.

2020-11-16 08:41 UTC, merged